# Generated by Django 4.0.3 on 2022-03-31 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_post_likecount_post_unlikecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.IntegerField(blank=True, default=0, verbose_name='count'),
        ),
    ]
