# Generated by Django 4.0.3 on 2022-03-31 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='count',
        ),
    ]
